export const CollectionMock = [
  {
    name: "Normal T-Shirt",
    price: 69.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "TShirts",
    subCategory: "Male",
  },
  {
    name: "Ultra T-Shirts",
    price: 69.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "TShirts",
    subCategory: "Female",
  },
  {
    name: "Camisetona",
    price: 59.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "TShirts",
    subCategory: "Male",
  },
  {
    name: "Camisetuxa",
    price: 59.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "TShirts",
    subCategory: "Female",
  },
  {
    name: "Normal Shorts",
    price: 49.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shorts",
    subCategory: "Male",
  },
  {
    name: "Ultra Shorts",
    price: 39.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shorts",
    subCategory: "Female",
  },
  {
    name: "Shortin",
    price: 49.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shorts",
    subCategory: "Male",
  },
  {
    name: "Carçola",
    price: 59.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shorts",
    subCategory: "Female",
  },
  {
    name: "Normal Shoes",
    price: 49.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shoes",
    subCategory: "Male",
  },
  {
    name: "Ultra Shoes",
    price: 39.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shoes",
    subCategory: "Female",
  },
  {
    name: "Sapatin",
    price: 49.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shoes",
    subCategory: "Male",
  },
  {
    name: "Chinela",
    price: 59.99,
    inStock: true,
    quantity: 20,
    colors: ["White", "Black", "Green", "Yellow"],
    sizes: ["P", "M", "G", "GG"],
    category: "Shoes",
    subCategory: "Female",
  },
];
